### ISSUE TITLE
Cancelled - Output folder does not contain frames

### ISSUE THREAD

**Issue by 12ben** [n00mkrad/flowframes#2] opened 2020-11-25 12:21 UTC
When I choose RIFE,   this message pops up.

**Comment by n00mkrad** [comment] 2020-11-26 19:30
Please reproduce this and then send all logs from FlowframesData/logs/.

**Comment by 12ben** [comment] 2020-11-27 03:02
I moved files to D:\tools\FlowframesAppV14\FlowframesData\pkgs\rife-cuda as the log said.
**rife-cuda-log**
11-27-2020 10:56:47: Changing working dir to D:\tools\FlowframesAppV14\FlowframesData\pkgs\rife-cuda
11-27-2020 10:56:47: Added D:\tools\FlowframesAppV14\FlowframesData\pkgs\rife-cuda to PATH
11-27-2020 10:56:49: [E] Traceback (most recent call last):
11-27-2020 10:56:49: [E]   File "interp-parallel.py", line 53, in <module>
11-27-2020 10:56:49: [E]     h, w, _ = frame.shape
11-27-2020 10:56:49: [E] AttributeError: 'NoneType' object has no attribute 'shape'
11-27-2020 10:56:50: [E] 
11-27-2020 10:58:3: Changing working dir to D:\tools\FlowframesAppV14\FlowframesData\pkgs\rife-cuda
11-27-2020 10:58:3: Added D:\tools\FlowframesAppV14\FlowframesData\pkgs\rife-cuda to PATH
11-27-2020 10:58:4: [E] Traceback (most recent call last):
11-27-2020 10:58:4: [E]   File "interp-parallel.py", line 53, in <module>
11-27-2020 10:58:4: [E]     h, w, _ = frame.shape
11-27-2020 10:58:4: [E] AttributeError: 'NoneType' object has no attribute 'shape'
11-27-2020 10:58:4: [E] 

**sessionlog**
11-27-2020 10:56:21: DeleteIfExists: D:/tools/FlowframesAppV14/Flowframes.exe.old
11-27-2020 10:56:21: Init NvApi
11-27-2020 10:56:21: PkgInstaller.IsInstalled - Checking for pkg with filename av.7z
11-27-2020 10:56:21: PkgInstaller.IsInstalled - Checking for pkg with filename licenses.7z
11-27-2020 10:56:23: Flowframes is up to date.
11-27-2020 10:56:35: Your file seems to be on an HDD or USB device. It is recommended to interpolate videos on an SSD drive for best performance.
11-27-2020 10:56:35: Video FPS (Loaded from fps.ini): 0 - Total Number Of Frames: 128
11-27-2020 10:56:41: PkgInstaller.IsAiAvailable - Checking for AI RIFE_CUDA
11-27-2020 10:56:41: PkgInstaller.IsInstalled - Checking for pkg with filename rife-cuda.7z
11-27-2020 10:56:41: DeleteIfExists: D:\Desktop\19-temp
11-27-2020 10:56:41: Starting...
11-27-2020 10:56:43: Running AI...
11-27-2020 10:56:43: PkgInstaller.IsInstalled - Checking for pkg with filename py.7z
11-27-2020 10:56:43: Checking if system Python is available...
11-27-2020 10:56:43: [DepCheck] CMD: /C python -V
11-27-2020 10:56:43: [DepCheck] System Python Check Output: Python 3.7.8
11-27-2020 10:56:43: [DepCheck] Sys Python Ver: Python 3.7.8
11-27-2020 10:56:43: Running RIFE (interp-parallel.py)...
11-27-2020 10:56:43: cmd.exe /C cd /D "D:\tools\FlowframesAppV14\FlowframesData\pkgs\rife-cuda" & set CUDA_VISIBLE_DEVICES=0 & python interp-parallel.py  --input "D:\Desktop\19-temp\frames" --times 1 --imgformat png
11-27-2020 10:56:50: Done running RIFE - Interpolation took 06s
11-27-2020 10:56:50: Cancelled.
11-27-2020 10:56:50: DeleteIfExists: D:\Desktop\19-temp
11-27-2020 10:56:50: Cancelled interpolation.
11-27-2020 10:57:36: Message: Cancelled:

Output folder does not contain frames - An error must have occured during interpolation!
11-27-2020 10:57:36: Deleting temporary files...
11-27-2020 10:57:36: Cleanup Error: 未能找到路径“D:\Desktop\19-temp”的一部分。
11-27-2020 10:57:36: Total processing time: 52s
11-27-2020 10:57:36: Done interpolating!
11-27-2020 10:57:54: Your file seems to be on an HDD or USB device. It is recommended to interpolate videos on an SSD drive for best performance.
11-27-2020 10:57:54: Video FPS (Loaded from fps.ini): 0 - Total Number Of Frames: 128
11-27-2020 10:58:1: PkgInstaller.IsAiAvailable - Checking for AI RIFE_CUDA
11-27-2020 10:58:1: PkgInstaller.IsInstalled - Checking for pkg with filename rife-cuda.7z
11-27-2020 10:58:1: DeleteIfExists: D:\tools\FlowframesAppV14\FlowframesData\pkgs\rife-cuda\19-temp
11-27-2020 10:58:1: Starting...
11-27-2020 10:58:1: Running AI...
11-27-2020 10:58:1: PkgInstaller.IsInstalled - Checking for pkg with filename py.7z
11-27-2020 10:58:1: Running RIFE (interp-parallel.py)...
11-27-2020 10:58:1: cmd.exe /C cd /D "D:\tools\FlowframesAppV14\FlowframesData\pkgs\rife-cuda" & set CUDA_VISIBLE_DEVICES=0 & python interp-parallel.py  --input "D:\tools\FlowframesAppV14\FlowframesData\pkgs\rife-cuda\19-temp\frames" --times 1 --imgformat png
11-27-2020 10:58:4: Done running RIFE - Interpolation took 03s
11-27-2020 10:58:4: Cancelled.
11-27-2020 10:58:4: DeleteIfExists: D:\tools\FlowframesAppV14\FlowframesData\pkgs\rife-cuda\19-temp
11-27-2020 10:58:5: Cancelled interpolation.

**Comment by public-profile-test** [comment] 2020-12-02 09:15
I got the popup with the same error message, but my log file includes below lines which I think might be useful.

> rife-cuda-log.txt

```
12-2-2020 16:29:30: [E] Traceback (most recent call last):
12-2-2020 16:29:30: [E]   File "interp-parallel.py", line 138, in <module>
12-2-2020 16:29:30: [E]     inferences = make_inference(model, I0, I1, exp=args.times)
12-2-2020 16:29:30: [E]   File "interp-parallel.py", line 110, in make_inference
12-2-2020 16:29:30: [E]     middle = model.inference(I0, I1)
12-2-2020 16:29:30: [E]   File "D:\Apps\Flowframes\FlowframesData\pkgs\rife-cuda\model\RIFE.py", line 207, in inference
12-2-2020 16:29:30: [E]     return self.predict(imgs, flow, training=False).detach()
12-2-2020 16:29:30: [E]   File "D:\Apps\Flowframes\FlowframesData\pkgs\rife-cuda\model\RIFE.py", line 191, in predict
12-2-2020 16:29:30: [E]     refine_output, warped_img0, warped_img1, warped_img0_gt, warped_img1_gt = self.fusionnet(
12-2-2020 16:29:30: [E]   File "D:\Apps\Flowframes\FlowframesData\pkgs\py\Lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
12-2-2020 16:29:30: [E]     result = self.forward(*input, **kwargs)
12-2-2020 16:29:30: [E]   File "D:\Apps\Flowframes\FlowframesData\pkgs\rife-cuda\model\RIFE.py", line 118, in forward
12-2-2020 16:29:30: [E]     x = self.up3(torch.cat((x, s0), 1))
12-2-2020 16:29:30: [E]   File "D:\Apps\Flowframes\FlowframesData\pkgs\py\Lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
12-2-2020 16:29:30: [E]     result = self.forward(*input, **kwargs)
12-2-2020 16:29:30: [E]   File "D:\Apps\Flowframes\FlowframesData\pkgs\py\Lib\site-packages\torch\nn\modules\container.py", line 117, in forward
12-2-2020 16:29:30: [E]     input = module(input)
12-2-2020 16:29:30: [E]   File "D:\Apps\Flowframes\FlowframesData\pkgs\py\Lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
12-2-2020 16:29:30: [E]     result = self.forward(*input, **kwargs)
12-2-2020 16:29:30: [E]   File "D:\Apps\Flowframes\FlowframesData\pkgs\py\Lib\site-packages\torch\nn\modules\conv.py", line 905, in forward
12-2-2020 16:29:30: [E]     return F.conv_transpose2d(
12-2-2020 16:29:30: [E] RuntimeError: CUDA out of memory. Tried to allocate 60.00 MiB (GPU 0; 6.00 GiB total capacity; 348.98 MiB already allocated; 8.99 MiB free; 444.00 MiB reserved in total by PyTorch)
```

**Comment by NAXX2008** [comment] 2020-12-02 09:37
BTW, one piece of video in 20FPS triggerred this problem but another one in 25FPS didn't. They are both 720p and encoded by x265, file size about 20MB.

**Comment by n00mkrad** [comment] 2020-12-02 14:26
Make sure you try to reboot first, maybe something is blocking the CUDA memory.

**Comment by NAXX2008** [comment] 2020-12-02 15:41
RIFE dev suggests that the non-parallel edition may address it.

> https://github.com/hzwer/arXiv2020-RIFE/issues/43#issuecomment-737149557

> In other words, we think that continuing to maintain a single-card parallel version is likely to introduce new problems, so please re-integrate inference_video.py.

**Comment by n00mkrad** [comment] 2020-12-02 16:19
> RIFE dev suggests that the non-parallel edition may address it.
> 
> > [hzwer/arXiv2020-RIFE#43 (comment)](https://github.com/hzwer/arXiv2020-RIFE/issues/43#issuecomment-737149557)
> 
> > In other words, we think that continuing to maintain a single-card parallel version is likely to introduce new problems, so please re-integrate inference_video.py.

I can't use the official code because it does not support image sequences.
I can try converting the code to make that work though.

**Comment by NAXX2008** [comment] 2020-12-03 09:26
A minor suggestion from me is to include critical error message produced by 3rd party libs, at least a prompt with log path. The concern is, I think the problem I met has different root cause than the original poster's, however, we got exactly same popup. It will also improve communication for issues (if any) in the future, I think.

**Comment by hzwer** [comment] 2020-12-03 10:05
RIFE supports image format input now.

**Comment by n00mkrad** [comment] 2020-12-03 11:52
> A minor suggestion from me is to include critical error message produced by 3rd party libs, at least a prompt with log path. The concern is, I think the problem I met has different root cause than the original poster's, however, we got exactly same popup. It will also improve communication for issues (if any) in the future, I think.

Error handling is improving in every version, especially v17, which will print better Pytorch/CUDA errors.

**Comment by n00mkrad** [comment] 2020-12-03 11:52
v18 will use the latest code by hzwer which should be more stable.

**Comment by n00mkrad** [comment] 2020-12-24 11:11
Closing for now.

**Closed by n00mkrad** 2020-12-24 11:11 UTC
