### ISSUE TITLE
1.40 Rife 4.6 does not work with GIF format

### ISSUE THREAD

**Issue by marmosetjones** [n00mkrad/flowframes#213] opened 2023-02-26 10:11 UTC
Rife 4.6 does not work with GIF format in the 1.40 release.
The error I receive is:
Unhandled Thread Exception!

Sequence contains no elements

Stack Trace:
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Flowframes.Interpolate.<PostProcessFrames>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Flowframes.Interpolate.<Start>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Flowframes.Form1.<runBtn_Click>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by n00mkrad** [comment] 2023-02-27 00:05
GIF Format as input or output, or both?

**Comment by marmosetjones** [comment] 2023-02-27 05:56
Output.

**Comment by n00mkrad** [comment] 2023-03-01 09:51
Cannot reproduce, please post your full settings

**Comment by marmosetjones** [comment] 2023-03-15 07:27
![image](https://user-images.githubusercontent.com/116389415/225236317-d518d238-79e1-44df-a010-18c4ffccf445.png)
![image](https://user-images.githubusercontent.com/116389415/225236412-a9d4cc3b-0e87-47d7-810b-f1d4008d4adb.png)
![image](https://user-images.githubusercontent.com/116389415/225236507-cf50ae6b-88ac-4bdc-9f3f-73019e26b1be.png)
![image](https://user-images.githubusercontent.com/116389415/225236560-cceaf252-338c-4eb7-b212-04199e468b83.png)
![image](https://user-images.githubusercontent.com/116389415/225236609-3c350580-680a-4b80-b253-dad84182dab5.png)
![image](https://user-images.githubusercontent.com/116389415/225236668-91d3b33c-8fa1-4da6-be85-99890aced510.png)
![image](https://user-images.githubusercontent.com/116389415/225236711-b3361596-1ce0-4932-8ad8-0b10e02aa36a.png)
 -pix_fmt yuv420p -vf scale=out_color_matrix=bt709 -colorspace bt709 -color_primaries bt709 -color_trc bt709 is used for the gif as well under additional (Output) arguments.

**Comment by n00mkrad** [comment] 2023-03-28 11:14
GIF does not support those args

**Comment by marmosetjones** [comment] 2023-03-28 11:59
It doesn't work even if I don't have any of that in the dev options.

**Comment by marmosetjones** [comment] 2023-03-29 02:06
Unhandled Thread Exception!

Sequence contains no elements

Stack Trace:
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Flowframes.Interpolate.<PostProcessFrames>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Flowframes.Interpolate.<Start>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Flowframes.Form1.<runBtn_Click>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

The error has been copied to the clipboard. Please inform the developer about this.

**Comment by n00mkrad** [comment] 2023-03-29 02:42
First of all, use RIFE NCNN VS

**Comment by marmosetjones** [comment] 2023-03-29 09:12
Thought cuda was for nvidia cards.

**Comment by n00mkrad** [comment] 2023-03-29 13:39
> Thought cuda was for nvidia cards.

NCNN is faster and can be used without having to write the frames to disk first.

**Comment by n00mkrad** [comment] 2023-03-30 12:09
I see. Can reproduce

**Comment by n00mkrad** [comment] 2023-03-30 12:10
> Also when using NCNN/VS for mp4 interpolated frames are deleted regardless of settings.

VS does not produce any interpolated frames

**Comment by n00mkrad** [comment] 2023-03-30 12:14
https://github.com/n00mkrad/flowframes/commit/693a2471d1e9f6362f0964ed33ddfa46f6f2a2c1

Fixed in next update

**Closed by n00mkrad** 2023-03-30 12:14 UTC

**Comment by marmosetjones** [comment] 2023-05-17 01:02
Could you please release the fix? I've been waiting over a month for it now. Side note, if you did release the fix it didn't work.
